# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Sync API Contract (push -> api-contract repo)

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout server repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Checkout api-contract repo
        uses: actions/checkout@v4
        with:
          repository: daechu5657/ui-framework-api-contract
          ref: main
          token: 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
          path: contract
